#!/bin/bash
# add docker install 
# sudo -i
echo "installing apt-file"
echo
sudo apt-get install file
echo "updating apt-file"
echo
sudo sudo apt-file update
echo "installing mesa-utils" 
echo
sudo apt-get install mesa-utils
echo "installing libmesa-dev"
echo
sudo apt-get install libmesa-dev 
echo "installing mesa-common-dev"
echo
sudo apt install mesa-common-dev
echo "installing freeglut"
echo
sudo apt install libglu1-mesa-dev freeglut3-dev
echo "copying libglut.so to /usr/lib64"
echo
mkdir /usr/lib64
sudo cp ./libglut.so /usr/lib64/
sudo chmod o=rwx /usr/lib64/libglut.so
sudo chmod u=rwx /usr/lib64/libglut.so
echo "installing python"
echo
sudo apt-get install python
echo "installing pip"
echo 
sudo apt-get install python-pip
echo "installing requezts module for python"
echo
sudo pip install requests
echo "updating"
echo
sudo apt-get update
echo "upgrading"
echo
sudo apt-get upgrade
echo "Done"
